# Generated by Django 3.2.15 on 2023-07-21 09:06

from django.db import migrations, models
import hotel_booking.core.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=hotel_booking.core.models.upload_path, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
