# Generated by Django 3.2.15 on 2023-09-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelownerprofile',
            name='hotel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_name', to='hotel.hotel'),
        ),
    ]
