# Generated by Django 3.2.15 on 2023-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelownerprofile_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_date', models.DateField()),
                ('pay_method', models.CharField(max_length=100)),
                ('pay_status', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('cancel', 'Cancel')], default='pending', max_length=10)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bookings', models.IntegerField()),
                ('average_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
