# Generated by Django 3.2.15 on 2023-07-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('image', models.ImageField(upload_to='room_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('occupancy_adult', models.PositiveIntegerField()),
                ('occupancy_child', models.PositiveIntegerField()),
                ('features', models.TextField(blank=True)),
                ('total_rooms', models.PositiveIntegerField()),
                ('room_booked', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('room_photo', models.ManyToManyField(related_name='RoomPhotoes', to='room.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_with_breakfast', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_without_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('surge_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomtype'),
        ),
    ]
