# Generated by Django 3.2.15 on 2023-09-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelownerprofile_hotel'),
        ('room', '0003_rename_book_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupancy',
            options={},
        ),
        migrations.RemoveField(
            model_name='occupancy',
            name='room',
        ),
        migrations.AddField(
            model_name='occupancy',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
