# Generated by Django 3.2.15 on 2023-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20230915_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupancy',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_booked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HotelPhoto',
        ),
        migrations.DeleteModel(
            name='Occupancy',
        ),
    ]
