# Generated by Django 3.2.15 on 2023-08-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='order',
        ),
    ]
