# Generated by Django 3.2.15 on 2023-08-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20230808_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_photo',
        ),
        migrations.DeleteModel(
            name='HotelPhoto',
        ),
    ]
